sudo : required

services :
  - docker

before_install : 
  - docker build -t pajju1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pajju1/docker-react npm run test

language: generic 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-us-east-1-741360002972"
  bucket_path: "test"
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
